#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Monitor behavior configuration
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width        1
bspc config window_gap          8
bspc config top_padding        12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a install4j-burp-StartBurp state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Ghidra state=floating

compton &
feh --bg-scale $HOME/wallpapers/structure_glow_points.jpg
killall polybar ; polybar main &
setxkbmap -layout us -variant altgr-intl
wmname LG3D
